export enum NODE_ENV {
  /** 개발 환경 */
  DEVELOPMENT = 'development',

  /** 테스트 환경 */
  TEST = 'test',

  /** 운영 환경 */
  PRODUCTION = 'production',
}

export enum DB_NAME {
  ANT_STING = 'ant-sting',
}

export enum QUEUE_NAME {
  INVEST_REPORT_SCORE = 'INVEST_REPORT_SCORE',
  MARKET_INFO_REPORT_SCORE = 'MARKET_INFO_REPORT_SCORE',
  STOCK_REPORT_SCORE = 'STOCK_REPORT_SCORE',
  INDUSTRY_REPORT_SCORE = 'INDUSTRY_REPORT_SCORE',
  ECONOMY_REPORT_SCORE = 'ECONOMY_REPORT_SCORE',
  DEBENTURE_REPORT_SCORE = 'DEBENTURE_REPORT_SCORE',
  REPORT_SUMMARY = 'REPORT_SUMMARY',
}
