version: "3.8"

networks:
  network:

volumes:
  service_redis:
  service_mongo:
  service_grafana:

services:
  #  grafana:
  #    image: grafana/grafana
  #    ports:
  #      - '9111:3000'
  #    environment:
  #      - GF_AUTH_ANONYMOUS_ENABLED=true
  #    volumes:
  #      - service_grafana:/var/lib/grafana

  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    restart: always
    networks:
      - network
    ports:
      - "6379:6379"
    volumes:
      - service_redis:/data

  mongo:
    image: mongo:8
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rgb-stock
      MONGO_DATA_DIR: /data/db
    networks:
      - network
    volumes:
      - service_mongo:/data/db
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
      args:
        APP_NAME: api
    image: api:latest
    networks:
      - network
    env_file:
      - .env
    ports:
      - "3002:3002"

  agent:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
      args:
        APP_NAME: agent
    image: agent:latest
    networks:
      - network
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

  batch:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
      args:
        APP_NAME: batch
    image: batch:latest
    networks:
      - network
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

  consumer:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
      args:
        APP_NAME: consumer
    image: consumer:latest
    networks:
      - network
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
