version: "3.8"

networks:
  network:

volumes:
  service_redis:
  service_mongo:

services:
  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    restart: always
    networks:
      - network
    ports:
      - 6379:6379
    volumes:
      - service_redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rgb-stock
      MONGO_DATA_DIR: /data/db
    networks:
      - network
    volumes:
      - service_mongo:/data/db
    ports:
      - 27017:27017

  batch:
    image: ant-sting-batch
    networks:
      network:
    env_file:
      - .env
    command:
      - 'node'
      - './apps/batch/src/main.js'
      - ${BATCH_COMMAND}
      - ${BATCH_SUBCOMMAND}
#
  consumer:
    image: ant-sting-consumer
    networks:
      network:
    env_file:
      - .env

  agent:
    image: ant-sting-agent:latest
    networks:
      network:
    env_file:
      - .env


  kroki:
    image: yuzutech/kroki
    ports:
      - "8000:8000"