version: "3.8"

networks:
  network:

volumes:
  service_grafana:
  service_redis:
  service_mongo:
  service_ollama:
  service_open_webui:
#  service_s3:

services:
  grafana:
    image: grafana/grafana
    networks:
      - network
    ports:
      - '9111:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - service_grafana:/var/lib/grafana

  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    restart: always
    networks:
      - network
    ports:
      - 6379:6379
    volumes:
      - service_redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rgb-stock
      MONGO_DATA_DIR: /data/db
    networks:
      - network
    volumes:
      - service_mongo:/data/db
#      - ./mongo/mongodb.key:/etc/mongodb.key
    ports:
      - 27017:27017
#    command: mongod --replSet localDev --keyFile /etc/mongodb.key --bind_ip_all

#  minio_s3:
#    platform: linux/amd64
#    image: minio/minio
#    container_name: s3
#    networks:
#      - network
#    ports:
#      - 9000:9000
#      - 9001:9001
#    volumes:
#      - service_s3:/data
#    environment:
#      - MINIO_ROOT_USER=root
#      - MINIO_ROOT_PASSWORD=root
#    command: server /data --console-address ":9001"

  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - network
    ports:
      - 11434:11434
    volumes:
      - service_ollama:/root/.ollama


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - network
    ports:
      - 3000:8080
    environment:
      OLLAMA_BASE_URL: "http://192.168.1.109:11434"
    volumes:
      - service_open_webui:/app/backend/data

  ant-sting-batch:
    image: iamdap91/ant-sting-batch
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=batch
    command:
      - 'node'
      - './apps/batch/src/main.js'
      - ${BATCH_COMMAND}
      - ${BATCH_SUBCOMMAND}

  ant-sting-api:
    image: iamdap91/ant-sting-api
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=api
    ports:
      - "3002:3002"

  ant-sting-consumer:
    image: iamdap91/ant-sting-consumer
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=consumer

  ant-sting-agent:
    image: iamdap91/ant-sting-agent
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=agent

  proxy:
    image: nginx
    networks:
      - network
    env_file:
      - .env
    volumes:
      - ./tools/nginx.conf:/etc/nginx/nginx.conf
      - ${TLS_CERTIFICATION_PATH}:/etc/nginx/cert1.pem
      - ${TLS_PRIVATE_KEY_PATH}:/etc/nginx/privkey1.pem
    ports:
      - "80:80"
      - "443:443"
