version: "3.8"

networks:
  network:

volumes:
#  service_grafana:
  service_redis:
  service_mongo:
#  service_ollama:
#  service_open_webui:
#  service_s3:

services:
  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    restart: always
    networks:
      - network
    ports:
      - 6379:6379
    volumes:
      - service_redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rgb-stock
      MONGO_DATA_DIR: /data/db
    networks:
      - network
    volumes:
      - service_mongo:/data/db
#      - ./mongo/mongodb.key:/etc/mongodb.key
    ports:
      - 27017:27017

#  open-webui:
#    image: ghcr.io/open-webui/open-webui:main
#    container_name: open-webui
#    networks:
#      - network
#    ports:
#      - 3000:8080
#    environment:
#      OLLAMA_BASE_URL: "http://192.168.1.109:11434"
#    volumes:
#      - service_open_webui:/app/backend/data

  ant-sting-batch:
    image: iamdap91/ant-sting-batch
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=batch
    command:
      - 'node'
      - './apps/batch/src/main.js'
      - ${BATCH_COMMAND}
      - ${BATCH_SUBCOMMAND}

  ant-sting-consumer:
    image: iamdap91/ant-sting-consumer
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=consumer

  ant-sting-agent:
    image: iamdap91/ant-sting-agent
    platform: linux/amd64
    networks:
      network:
    env_file:
      - .env
    environment:
      - BUILD_SERVICE_NAME=agent


  kroki:
    image: yuzutech/kroki
    ports:
      - "8000:8000"