version: "3.8"

networks:
  network:

volumes:
  service_redis:
  service_mongo:
  service_grafana:

services:
  grafana:
    image: grafana/grafana
    ports:
      - '9111:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - service_grafana:/var/lib/grafana

  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    restart: always
    networks:
      - network
    ports:
      - 6379:6379
    volumes:
      - service_redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rgb-stock
      MONGO_DATA_DIR: /data/db
    networks:
      - network
    volumes:
      - service_mongo:/data/db
    ports:
      - 27017:27017

  batch:
    image: batch:latest
    networks:
      network:
    env_file:
      - .env
    command:
      - 'node'
      - './apps/batch/src/main.js'

  consumer:
    image: consumer:latest
    networks:
      network:
    env_file:
      - .env
    command:
      - 'node'
      - './apps/consumer/src/main.js'

  agent:
    image: agent:latest
    networks:
      network:
    env_file:
      - .env
    command:
      - 'node'
      - './apps/agent/src/main.js'
#
#  kroki:
#    image: yuzutech/kroki
#    ports:
#      - "8000:8000"
