version: '3.9'

volumes:
  grafana:
  minio:

services:
  grafana:
    image: grafana/grafana
    ports:
      - '9111:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana:/var/lib/grafana

  minio_s3:
    platform: linux/amd64
    image: minio/minio
    networks:
      - network
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio
    command: server /data --console-address ":9001"
