export const EXTERNAL_API_TOKEN = {
  SLACK_API: Symbol('SLACK_API'),
  KCIF_API: Symbol('KCIF_API'),
  NAVER_PAY_API: Symbol('NAVER_PAY_API'),
  POLY_MARKET_API: Symbol('POLY_MARKET_API'),
  SEC_API_SERVICE: Symbol('SEC_API_SERVICE'),
};

export const BROWSERS_TOKEN = {
  CHROMIUM: Symbol('CHROME'),
  FIREFOX: Symbol('FIREFOX'),
};

export const AI_TOKEN = {
  GEMINI: Symbol('GEMINI'),
};

export const MONGO_REPOSITORY_TOKEN = {
  PORTFOLIO: Symbol('PORTFOLIO'),
  ECONOMIC_INFORMATION: Symbol('ECONOMIC_INFORMATION'),
  ECONOMIC_INFORMATION_ANALYSIS: Symbol('ECONOMIC_INFORMATION_ANALYSIS'),
};

export const REDIS_REPOSITORY_TOKEN = {
  SEC_FEED: Symbol('SEC_FEED'),
  INVESTMENT: Symbol('INVESTMENT'),
};
