name: 배포 파이프 라인
on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        description: "서비스 이름"
        required: true
      buildServiceName:
        description: "빌드 서비스 이름(api, batch, consumer)"
        type: string
        required: true
      dockerPath:
        description: "DockerFile Path"
        type: string
        required: false
        default: "./tools/Dockerfile"
      deployEnv:
        description: "배포 환경 설정(test, production) - 현재는 사용하지 않음"
        type: string
        required: false
        default: "test"

env:
  SERVICE_NAME: ${{ inputs.serviceName }}
  BUILD_SERVICE_NAME: ${{ inputs.buildServiceName }}
  DOCKER_PATH: ${{ inputs.dockerPath }}
  #DEPLOY_ENV: ${{ inputs.deployEnv }}

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Short SHA
        id: slug
        run: echo "sha8=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.DOCKER_PATH }}"
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.slug.outputs.sha8 }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          build-args: |
            BUILD_SERVICE_NAME=${{ env.BUILD_SERVICE_NAME }}
