name: PR Checker
on:
  pull_request:
  push:
    branches:
      - main
      - test-server
      - hotfix/*

jobs:
  call-workflow:
    uses: "boostbrothers/.github-private/.github/workflows/pr-checker.yaml@main"
    with:
      testCmd: "npm run test"
      buildCmd: "npm run build"
      lintCmd: "npm run lint"
      nodeEnv: "node-18"
    secrets: inherit
