name: 설정_운영환경 배포
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
#  api:
#    uses: "./.github/workflows/build-and-deploy.yaml"
#    with:
#      serviceName: ant-sting-api
#      deployEnv: prod
#      buildServiceName: api
#    secrets: inherit
#
#  agent:
#    uses: "./.github/workflows/build-and-deploy.yaml"
#    with:
#      serviceName: ant-sting-agent
#      deployEnv: prod
#      buildServiceName: agent
#    secrets: inherit

  batch:
    uses: "./.github/workflows/build-and-deploy.yaml"
    with:
      serviceName: ant-sting-batch
      deployEnv: prod
      buildServiceName: batch
    secrets: inherit

  consumer:
    uses: "./.github/workflows/build-and-deploy.yaml"
    with:
      serviceName: ant-sting-consumer
      deployEnv: prod
      buildServiceName: consumer
    secrets: inherit
