name: 설정_개발환경 배포
on:
  workflow_dispatch:
  push:
    branches:
      - test-server

jobs:
  api:
    uses: "./.github/workflows/build-and-deploy.yaml"
    with:
      serviceName: ant-sting-api
      deployEnv: test
      buildServiceName: api
    secrets: inherit

  agent:
    uses: "./.github/workflows/build-and-deploy.yaml"
    with:
      serviceName: ant-sting-agent
      deployEnv: test
      buildServiceName: agent
    secrets: inherit

  batch:
    uses: "./.github/workflows/build-and-deploy.yaml"
    with:
      serviceName: ant-sting-batch
      deployEnv: test
      buildServiceName: batch
    secrets: inherit

  consumer:
    uses: "./.github/workflows/build-and-deploy.yaml"
    with:
      serviceName: ant-sting-consumer
      deployEnv: test
      buildServiceName: consumer
    secrets: inherit
